version: 0.2

phases:
  build:
    commands:
      - echo Packaging producer lambda
      - cd lambdas/producer
      - zip -r ../../producer.zip .
      - cd ../../

      - echo Packaging consumer lambda
      - cd lambdas/consumer
      - zip -r ../../consumer.zip .
      - cd ../../

      - echo Uploading producer to S3 bucket $ARTIFACT_BUCKET
      - aws s3 cp producer.zip s3://$ARTIFACT_BUCKET/lambdas/producer.zip

      - echo Uploading consumer to S3 bucket $ARTIFACT_BUCKET
      - aws s3 cp consumer.zip s3://$ARTIFACT_BUCKET/lambdas/consumer.zip

      - echo Uploading Glue scripts
      - aws s3 cp glue/raw_to_curated.py s3://$ARTIFACT_BUCKET/glue/raw_to_curated.py

      - echo Uploading Glue scripts
      - aws s3 cp glue/raw_to_curated.py s3://$ARTIFACT_BUCKET/glue/raw_to_curated.py
      - aws s3 cp glue/raw_to_curated_latest.py s3://$ARTIFACT_BUCKET/glue/raw_to_curated_latest.py


artifacts:
  files:
    - infra/template.yaml
