AWSTemplateFormatVersion: '2010-09-09'
Description: Earthquake Step Function

Resources:
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess

  EarthquakeStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: earthquake-pipeline
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: |
        REPLACE_ME
