AWSTemplateFormatVersion: '2010-09-09'
Description: Earthquake pipeline – Lambda, Step Functions, Glue, SNS (uses existing Kinesis)

Parameters:
  ArtifactBucket:
    Type: String
    Description: S3 bucket where CodeBuild uploads Lambda artifacts

Resources:
  #################################################
  # SNS (existing topic – DO NOT recreate)
  #################################################
  EarthquakeSNSTopic:
    Type: AWS::SNS::Topic
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TopicName: earthquake-alerts

  #################################################
  # IAM Role for Step Function
  #################################################
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - glue:StartJobRun
                  - sns:Publish
                Resource: "*"

  #################################################
  # IAM Role for Producer Lambda
  #################################################
  ProducerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ProducerKinesisPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecords
                Resource: arn:aws:kinesis:eu-west-2:430006376054:stream/prathyusha-earthquake-stream

  #################################################
  # Producer Lambda
  #################################################
  ProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: prathyusha-earthquake-producer
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !GetAtt ProducerLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: lambdas/producer.zip
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          KINESIS_STREAM_NAME: prathyusha-earthquake-stream

  #################################################
  # IAM Role for Consumer Lambda
  #################################################
  ConsumerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ConsumerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: arn:aws:sns:eu-west-2:430006376054:earthquake-alerts

  #################################################
  # Consumer Lambda
  #################################################
  ConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: prathyusha-earthquake-consumer
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !GetAtt ConsumerLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: lambdas/consumer.zip
      Timeout: 60
      MemorySize: 256

  #################################################
  # Kinesis → Consumer mapping (existing stream)
  #################################################
  ConsumerKinesisMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: arn:aws:kinesis:eu-west-2:430006376054:stream/prathyusha-earthquake-stream
      FunctionName: !Ref ConsumerLambda
      StartingPosition: LATEST
      BatchSize: 100

  #################################################
  # Step Function
  #################################################
  EarthquakeStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: earthquake-pipeline
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: |
        {
          "Comment": "Earthquake pipeline",
          "StartAt": "InvokeProducer",
          "States": {
            "InvokeProducer": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "prathyusha-earthquake-producer",
                "Payload": {}
              },
              "Retry": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "Next": "Wait"
            },
            "Wait": {
              "Type": "Wait",
              "Seconds": 60,
              "Next": "RunRawToCurated"
            },
            "RunRawToCurated": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Parameters": {
                "JobName": "prathyusha-earthquake-raw-to-curated"
              },
              "Next": "RunCuratedLatest"
            },
            "RunCuratedLatest": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Parameters": {
                "JobName": "prathyusha-earthquake-raw-to-curated_latest"
              },
              "End": true
            },
            "NotifyFailure": {
              "Type": "Task",
              "Resource": "arn:aws:states:::sns:publish",
              "Parameters": {
                "TopicArn": "arn:aws:sns:eu-west-2:430006376054:earthquake-alerts",
                "Message": "Earthquake pipeline failed"
              },
              "End": true
            }
          }
        }

  #################################################
  # Scheduled trigger (EventBridge)
  #################################################
  EarthquakePipelineSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(15 minutes)
      State: ENABLED
      Targets:
        - Arn: !Ref EarthquakeStateMachine
          Id: EarthquakeStepFunctionTarget
          RoleArn: !GetAtt StepFunctionRole.Arn

Outputs:
  StateMachineArn:
    Value: !Ref EarthquakeStateMachine
