AWSTemplateFormatVersion: '2010-09-09'
Description: Earthquake streaming pipeline with Step Functions, Lambda, Kinesis, Glue, DynamoDB, SNS

Parameters:
  ArtifactBucket:
    Type: String
    Description: S3 bucket used by CodePipeline to store Lambda artifacts

  ExistingDynamoDBTableName:
    Type: String
    Default: prathyusha-earthquakes-latest
    Description: Existing DynamoDB table for earthquake data

Resources:

  #################################################
  # IAM Role — Step Functions
  #################################################
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
                - events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - glue:StartJobRun
                  - sns:Publish
                  - states:StartExecution
                Resource: "*"

  #################################################
  # IAM Role — Producer Lambda
  #################################################
  ProducerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ProducerKinesisPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kinesis:PutRecords
                Resource: arn:aws:kinesis:eu-west-2:430006376054:stream/prathyusha-earthquake-stream

  #################################################
  # Producer Lambda
  #################################################
  ProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: prathyusha-earthquake-producer
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !GetAtt ProducerLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: lambdas/producer.zip
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          KINESIS_STREAM_NAME: prathyusha-earthquake-stream

  #################################################
  # IAM Role — Consumer Lambda
  #################################################
  ConsumerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ConsumerPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

              # DynamoDB (EXISTING TABLE)
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:DescribeTable
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ExistingDynamoDBTableName}

              # SNS
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: arn:aws:sns:eu-west-2:430006376054:earthquake-alerts

              # Kinesis READ
              - Effect: Allow
                Action:
                  - kinesis:GetRecords
                  - kinesis:GetShardIterator
                  - kinesis:DescribeStream
                  - kinesis:DescribeStreamSummary
                  - kinesis:ListShards
                  - kinesis:ListStreams
                Resource: arn:aws:kinesis:eu-west-2:430006376054:stream/prathyusha-earthquake-stream

  #################################################
  # Consumer Lambda
  #################################################
  ConsumerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: prathyusha-earthquake-consumer
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !GetAtt ConsumerLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucket
        S3Key: lambdas/consumer.zip
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          TABLE_NAME: !Ref ExistingDynamoDBTableName
          SNS_TOPIC_ARN: arn:aws:sns:eu-west-2:430006376054:earthquake-alerts

  #################################################
  # Kinesis → Consumer trigger
  #################################################
  ConsumerKinesisMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: arn:aws:kinesis:eu-west-2:430006376054:stream/prathyusha-earthquake-stream
      FunctionName: !Ref ConsumerLambda
      StartingPosition: LATEST
      BatchSize: 100
      Enabled: true

  #################################################
  # Step Function
  #################################################
  EarthquakeStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: earthquake-pipeline
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: |
        {
          "Comment": "Earthquake pipeline with retries and SNS failure notification",
          "StartAt": "InvokeProducer",
          "States": {
            "InvokeProducer": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "prathyusha-earthquake-producer"
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 2,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "Next": "WaitForData"
            },

            "WaitForData": {
              "Type": "Wait",
              "Seconds": 60,
              "Next": "RunCuratedHistoryJob"
            },

            "RunCuratedHistoryJob": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Parameters": {
                "JobName": "prathyusha-earthquake-raw-to-curated"
              },
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "Next": "RunCuratedLatestJob"
            },

            "RunCuratedLatestJob": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Parameters": {
                "JobName": "prathyusha-earthquake-raw-to-curated_latest"
              },
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "End": true
            },

            "NotifyFailure": {
              "Type": "Task",
              "Resource": "arn:aws:states:::sns:publish",
              "Parameters": {
                "TopicArn": "arn:aws:sns:eu-west-2:430006376054:earthquake-alerts",
                "Subject": "❌ Earthquake Pipeline Failed",
                "Message": "The earthquake Step Function execution failed. Check CloudWatch logs."
              },
              "End": true
            }
          }
        }

  #################################################
  # EventBridge Schedule
  #################################################
  EarthquakePipelineSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(15 minutes)
      State: ENABLED
      Targets:
        - Arn: !Ref EarthquakeStateMachine
          Id: EarthquakePipelineTarget
          RoleArn: !GetAtt StepFunctionRole.Arn

Outputs:
  StateMachineArn:
    Value: !Ref EarthquakeStateMachine
