AWSTemplateFormatVersion: '2010-09-09'
Description: Earthquake Step Function with Producer Lambda

Resources:

  # -------------------------------------------------
  # IAM Role for Step Functions
  # -------------------------------------------------
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                  - glue:StartJobRun
                  - sns:Publish
                Resource: "*"

  # -------------------------------------------------
  # IAM Role for Lambda
  # -------------------------------------------------
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # -------------------------------------------------
  # Producer Lambda (code comes from S3)
  # -------------------------------------------------
  ProducerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: prathyusha-earthquake-producer
      Runtime: python3.11
      Handler: app.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: earthquake-pipeline-artifacts
        S3Key: lambdas/producer.zip
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          KINESIS_STREAM_NAME: prathyusha-earthquake-stream
          USGS_URL: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson

  # -------------------------------------------------
  # Step Function
  # -------------------------------------------------
  EarthquakeStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: earthquake-pipeline
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionString: |
        {
          "Comment": "Earthquake pipeline with retries and SNS failure notification",
          "QueryLanguage": "JSONata",
          "StartAt": "InvokeProducer",
          "States": {
            "InvokeProducer": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Arguments": {
                "FunctionName": "arn:aws:lambda:eu-west-2:430006376054:function:prathyusha-earthquake-producer",
                "Payload": {}
              },
              "Retry": [
                {
                  "ErrorEquals": [
                    "Lambda.ServiceException",
                    "Lambda.AWSLambdaException",
                    "Lambda.SdkClientException",
                    "Lambda.TooManyRequestsException"
                  ],
                  "IntervalSeconds": 2,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "Next": "Wait"
            },
            "Wait": {
              "Type": "Wait",
              "Seconds": 60,
              "Next": "RunCuratedHistoryJob"
            },
            "RunCuratedHistoryJob": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Arguments": {
                "JobName": "prathyusha-earthquake-raw-to-curated"
              },
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "Next": "RunCuratedLatestJob"
            },
            "RunCuratedLatestJob": {
              "Type": "Task",
              "Resource": "arn:aws:states:::glue:startJobRun",
              "Arguments": {
                "JobName": "prathyusha-earthquake-raw-to-curated_latest"
              },
              "Catch": [
                {
                  "ErrorEquals": ["States.ALL"],
                  "Next": "NotifyFailure"
                }
              ],
              "End": true
            },
            "NotifyFailure": {
              "Type": "Task",
              "Resource": "arn:aws:states:::sns:publish",
              "Arguments": {
                "TopicArn": "arn:aws:sns:eu-west-2:430006376054:earthquake-alerts",
                "Subject": "❌ Earthquake Pipeline Failed",
                "Message": "The earthquake Step Function execution has failed. Please check CloudWatch Logs for details."
              },
              "End": true
            }
          }
        }
